'use client';

import { useStore } from '../../lib/store';
import { Metric } from '../../components/Metric';
import { Users, TrendingUp, ArrowDown, Activity, Globe, Zap } from 'lucide-react';

export default function UserMetricsPage() {
  const { inputs, derivations, updateInput } = useStore();

  const funnelSteps = [
    {
      name: 'Monthly Active Users (MAU)',
      value: inputs.MAU,
      formatted: `${(inputs.MAU / 1000000).toFixed(0)}M`,
      unit: 'users/mo',
      pct: 100,
      badge: 'Base Input',
      desc: 'Total registered user cohort logging in at least once in a 30-day window.',
      color: 'from-blue-500/20 to-indigo-500/20 border-indigo-500/30 text-indigo-300',
      metric: {
        value: inputs.MAU,
        unit: 'users/mo',
        formulaText: 'MAU = Baseline Platform Cohort Input',
        substitutions: `MAU = ${inputs.MAU.toLocaleString()} users`,
        humanExplanation: 'The total universe of active registered accounts across web, iOS, and Android platforms in a given calendar month.',
        dependsOn: ['MAU'],
      },
    },
    {
      name: 'Daily Active Users (DAU)',
      value: derivations.dau.value,
      formatted: `${(derivations.dau.value / 1000000).toFixed(1)}M`,
      unit: 'users/day',
      pct: inputs.DAU_PCT,
      badge: `${inputs.DAU_PCT}% DAU/MAU`,
      desc: 'Active unique users on platform within any 24-hour cycle.',
      color: 'from-indigo-500/20 to-purple-500/20 border-purple-500/30 text-purple-300',
      metric: derivations.dau,
    },
    {
      name: 'Peak Concurrent Users (PCU)',
      value: derivations.pcu.value,
      formatted: `${(derivations.pcu.value / 1000).toFixed(0)}k`,
      unit: 'concurrent users',
      pct: (derivations.pcu.value / inputs.MAU) * 100,
      badge: `${inputs.PEAK_CONCURRENT_PCT}% of DAU`,
      desc: 'Simultaneous active sessions during highest traffic surge of the day.',
      color: 'from-purple-500/20 to-pink-500/20 border-pink-500/30 text-pink-300',
      metric: derivations.pcu,
    },
    {
      name: 'Raw API RPS',
      value: derivations.rawRps.value,
      formatted: `${Math.round(derivations.rawRps.value).toLocaleString()}`,
      unit: 'req/s',
      pct: 50,
      badge: `${inputs.ACTIONS_PER_SESSION} acts / ${inputs.PEAK_DURATION_SEC / 3600}h`,
      desc: 'Theoretical unbuffered request throughput generated by concurrent user sessions.',
      color: 'from-pink-500/20 to-rose-500/20 border-rose-500/30 text-rose-300',
      metric: derivations.rawRps,
    },
    {
      name: 'Peak API RPS (Anchor)',
      value: derivations.peakRps.value,
      formatted: `${Math.round(derivations.peakRps.value).toLocaleString()}`,
      unit: 'req/s',
      pct: 100,
      badge: `${inputs.SAFETY_BUFFER}x buffer × ${inputs.Spike_Multiplier}x spike`,
      desc: 'The definitive anchor capacity number sizing all downstream gateways, microservices, databases, and message brokers.',
      color: 'from-rose-500/30 to-amber-500/30 border-amber-500/40 text-amber-300',
      metric: derivations.peakRps,
    },
  ];

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-16 font-sans">
      {/* Header */}
      <div className="rounded-xl border border-white/[0.08] bg-[#0d0e15] p-5 shadow-lg flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-mono uppercase tracking-wider bg-indigo-500/10 border border-indigo-500/20 text-indigo-400">
              Sheet 02
            </span>
            <h1 className="text-xl font-bold text-white tracking-tight">User Metrics & Funnel Model</h1>
          </div>
          <p className="text-xs text-zinc-400 mt-1">
            Top-of-funnel traffic decomposition from aggregate 10M MAU down to Peak API RPS.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="rounded-lg border border-white/[0.08] bg-black/40 px-3 py-1.5 text-right">
            <span className="text-[10px] uppercase text-zinc-500 block font-mono">Anchor Peak RPS</span>
            <span className="font-mono text-base font-bold text-amber-300">
              {Math.round(derivations.peakRps.value).toLocaleString()}
            </span>
          </div>
        </div>
      </div>

      {/* Visual Funnel Cards */}
      <div className="space-y-2.5">
        <h2 className="text-xs font-mono font-semibold uppercase tracking-wider text-zinc-400 flex items-center gap-1.5">
          <TrendingUp size={14} className="text-indigo-400" />
          Interactive Request Funnel Cascade
        </h2>

        <div className="space-y-2">
          {funnelSteps.map((step, idx) => (
            <div key={step.name} className="relative">
              <div
                className={`rounded-lg border bg-gradient-to-r ${step.color} p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-sm transition-all hover:scale-[1.005]`}
              >
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-semibold text-zinc-400">0{idx + 1}.</span>
                    <h3 className="text-sm font-bold text-white tracking-tight">{step.name}</h3>
                    <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-black/30 border border-white/[0.08] text-zinc-300">
                      {step.badge}
                    </span>
                  </div>
                  <p className="text-xs text-zinc-300 max-w-xl">{step.desc}</p>
                </div>

                <div className="flex items-center gap-3 self-end sm:self-center">
                  <Metric name={step.name} metric={step.metric} size="lg" showLabel={false} />
                </div>
              </div>

              {idx < funnelSteps.length - 1 && (
                <div className="flex justify-center my-0.5">
                  <ArrowDown size={14} className="text-zinc-600" />
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Detailed Calculations Table */}
      <div className="rounded-xl border border-white/[0.08] bg-[#0e1017] p-5 shadow-sm space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-white/[0.06]">
          <h2 className="text-xs font-mono font-semibold uppercase tracking-wider text-zinc-200 flex items-center gap-2">
            <Zap size={14} className="text-indigo-400" />
            Mathematical Derivation Table
          </h2>
          <span className="text-[11px] text-zinc-500 font-mono">Click metric badges to inspect formulas</span>
        </div>

        <div className="divide-y divide-white/[0.04]">
          <div className="py-2.5 flex items-center justify-between">
            <div>
              <span className="text-xs font-medium text-zinc-200">1. Daily Active Users (DAU)</span>
              <p className="text-[11px] text-zinc-500">MAU × (DAU% / 100)</p>
            </div>
            <Metric name="DAU" metric={derivations.dau} />
          </div>

          <div className="py-2.5 flex items-center justify-between">
            <div>
              <span className="text-xs font-medium text-zinc-200">2. Peak Concurrent Users (PCU)</span>
              <p className="text-[11px] text-zinc-500">DAU × (Peak_Concurrent% / 100)</p>
            </div>
            <Metric name="PCU" metric={derivations.pcu} />
          </div>

          <div className="py-2.5 flex items-center justify-between">
            <div>
              <span className="text-xs font-medium text-zinc-200">3. Raw API RPS</span>
              <p className="text-[11px] text-zinc-500">(PCU × Actions/Session) / Peak_Duration_sec</p>
            </div>
            <Metric name="Raw RPS" metric={derivations.rawRps} />
          </div>

          <div className="py-2.5 flex items-center justify-between bg-indigo-950/20 px-2 rounded">
            <div>
              <span className="text-xs font-semibold text-indigo-200">4. Peak API RPS (Anchor)</span>
              <p className="text-[11px] text-indigo-400/80">Raw_RPS × Safety_Buffer × Spike_Multiplier</p>
            </div>
            <Metric name="Peak RPS" metric={derivations.peakRps} />
          </div>

          <div className="py-2.5 flex items-center justify-between">
            <div>
              <span className="text-xs font-medium text-zinc-200">5. Daily API Transactions</span>
              <p className="text-[11px] text-zinc-500">DAU × Actions/Session</p>
            </div>
            <Metric name="Daily Reqs" metric={derivations.dailyReqs} />
          </div>

          <div className="py-2.5 flex items-center justify-between">
            <div>
              <span className="text-xs font-medium text-zinc-200">6. Monthly API Transactions</span>
              <p className="text-[11px] text-zinc-500">Daily_Requests × 30 days</p>
            </div>
            <Metric name="Monthly Reqs" metric={derivations.monthlyReqs} />
          </div>

          <div className="py-2.5 flex items-center justify-between">
            <div>
              <span className="text-xs font-medium text-zinc-200">7. Peak Bandwidth (MB/s)</span>
              <p className="text-[11px] text-zinc-500">Peak_RPS × (Response_KB + Request_KB) / 1024</p>
            </div>
            <Metric name="Peak Bandwidth" metric={derivations.peakBandwidthMBps} />
          </div>

          <div className="py-2.5 flex items-center justify-between">
            <div>
              <span className="text-xs font-medium text-zinc-200">8. Peak Line Speed (Gbps)</span>
              <p className="text-[11px] text-zinc-500">Peak_MBps × 8 / 1000</p>
            </div>
            <Metric name="Line Speed" metric={derivations.peakBandwidthGbps} />
          </div>

          <div className="py-2.5 flex items-center justify-between">
            <div>
              <span className="text-xs font-medium text-zinc-200">9. Daily Egress Volume (GB)</span>
              <p className="text-[11px] text-zinc-500">Daily_Requests × AVG_RESPONSE_SIZE_KB / 1024²</p>
            </div>
            <Metric name="Daily Egress" metric={derivations.dailyEgressGb} />
          </div>

          <div className="py-2.5 flex items-center justify-between">
            <div>
              <span className="text-xs font-medium text-zinc-200">10. Monthly Egress Volume (TB)</span>
              <p className="text-[11px] text-zinc-500">Daily_Egress_GB × 30 / 1024</p>
            </div>
            <Metric name="Monthly Egress" metric={derivations.monthlyEgressTb} />
          </div>
        </div>
      </div>
    </div>
  );
}
