'use client';

import { useState, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { Info, Check, Copy, ArrowUpRight, Zap, X, Calculator, Layers } from 'lucide-react';
import { MetricResult } from '../lib/derivations';
import { useStore } from '../lib/store';
import clsx from 'clsx';

interface MetricProps {
  name: string;
  metric: MetricResult;
  size?: 'sm' | 'md' | 'lg';
  className?: string;
  showLabel?: boolean;
}

export function Metric({ name, metric, size = 'md', className, showLabel = true }: MetricProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [mounted, setMounted] = useState(false);
  const { highlightedDependencies, setHighlightedDependencies } = useStore();

  useEffect(() => {
    setMounted(true);
  }, []);

  const isHighlighted = metric.dependsOn.some((dep) =>
    highlightedDependencies.includes(dep)
  );

  // Close modal on Escape key press
  useEffect(() => {
    if (!open) return;
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setOpen(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [open]);

  const formatFullContent = useCallback(() => {
    const formattedVal =
      typeof metric.value === 'number'
        ? metric.value.toLocaleString(undefined, { maximumFractionDigits: 2 })
        : metric.value;

    const sections = [
      `==================================================`,
      `SYSTEM DESIGN METRIC: ${name}`,
      `==================================================`,
      `Computed Result: ${formattedVal} ${metric.unit || ''}`.trim(),
      ``,
      `[1] FORMULA EXPRESSION:`,
      `${metric.formulaText}`,
    ];

    if (metric.substitutions && metric.substitutions !== metric.formulaText) {
      sections.push(``, `[2] STEP-BY-STEP SUBSTITUTION:`, `${metric.substitutions}`);
    }

    if (metric.humanExplanation) {
      sections.push(``, `[3] ARCHITECTURAL CONTEXT & IMPORTANCE:`, `${metric.humanExplanation}`);
    }

    if (metric.dependsOn && metric.dependsOn.length > 0) {
      sections.push(``, `[4] INPUT DEPENDENCIES:`, `${metric.dependsOn.join(', ')}`);
    }

    sections.push(
      ``,
      `--------------------------------------------------`,
      `Generated by System Design`
    );

    return sections.join('\n');
  }, [name, metric]);

  const copyFullContent = async (e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    try {
      const fullText = formatFullContent();
      await navigator.clipboard.writeText(fullText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
  };

  const formattedValue =
    typeof metric.value === 'number'
      ? metric.value >= 1000000
        ? (metric.value / 1000000).toFixed(2).replace(/\.00$/, '') + 'M'
        : metric.value >= 10000
        ? (metric.value / 1000).toFixed(1).replace(/\.0$/, '') + 'k'
        : metric.value % 1 !== 0
        ? metric.value.toFixed(2).replace(/\.00$/, '')
        : metric.value.toLocaleString()
      : metric.value;

  const fullDisplayVal =
    typeof metric.value === 'number'
      ? metric.value.toLocaleString(undefined, { maximumFractionDigits: 2 })
      : metric.value;

  const fullTextTooltip = `${name}: ${fullDisplayVal} ${metric.unit || ''} — Click to inspect formula & derivations`;

  return (
    <div className={clsx('relative inline-block max-w-full', className)}>
      {/* Trigger Button */}
      <button
        type="button"
        onClick={() => setOpen(true)}
        title={fullTextTooltip}
        className={clsx(
          'group flex items-center gap-1.5 rounded-md border text-left transition-all duration-150 max-w-full truncate cursor-pointer',
          size === 'sm' && 'px-2 py-0.5 text-xs',
          size === 'md' && 'px-2.5 py-1 text-xs',
          size === 'lg' && 'px-3 py-1.5 text-sm',
          isHighlighted
            ? 'border-indigo-500/60 bg-indigo-950/40 text-indigo-200 shadow-[0_0_12px_rgba(99,102,241,0.25)]'
            : 'border-white/[0.08] bg-[#0e1017] hover:border-indigo-500/40 hover:bg-[#151823] text-zinc-100'
        )}
      >
        {showLabel && (
          <span className="text-[11px] font-medium text-zinc-400 group-hover:text-zinc-300 truncate" title={name}>
            {name}
          </span>
        )}
        <span className="font-mono font-semibold tracking-tight text-zinc-100 truncate" title={String(metric.value)}>
          {formattedValue}
        </span>
        {metric.unit && (
          <span className="text-[10px] font-medium text-zinc-500 flex-shrink-0" title={metric.unit}>
            {metric.unit}
          </span>
        )}
        <Info
          size={12}
          className="text-zinc-500 opacity-70 transition-all group-hover:opacity-100 group-hover:text-indigo-400 group-hover:scale-110 flex-shrink-0"
        />
      </button>

      {/* Centered Modal Window with 20% side margins and 30% top/bottom margins - Rendered in Portal with z-[9999] */}
      {open && mounted && createPortal(
        <div
          className="fixed inset-0 z-[9999] flex items-center justify-center p-3 sm:p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-150"
          onClick={() => setOpen(false)}
        >
          <div
            className="relative w-[95vw] sm:w-[85vw] md:w-[60vw] max-w-[95vw] md:max-w-[60vw] max-h-[85vh] md:max-h-[46vh] flex flex-col rounded-2xl border border-white/[0.12] bg-[#0c0d14] text-zinc-100 shadow-2xl overflow-hidden font-sans animate-in zoom-in-95 duration-150"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header with Title, Copy Clip Icon, and Close X Icon */}
            <div className="flex items-center justify-between px-3.5 sm:px-5 py-2.5 sm:py-3 border-b border-white/[0.08] bg-[#10121b] flex-shrink-0">
              <div className="flex items-center gap-2 sm:gap-2.5 min-w-0">
                <div className="p-1.5 sm:p-2 rounded-lg bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 flex-shrink-0">
                  <Calculator size={15} />
                </div>
                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="text-[9px] sm:text-[10px] font-mono uppercase tracking-wider px-1.5 py-0.2 rounded bg-white/[0.06] text-zinc-400">
                      Formula Derivation
                    </span>
                  </div>
                  <h2 className="text-xs sm:text-sm font-bold text-white tracking-tight truncate mt-0.5" title={name}>
                    {name}
                  </h2>
                </div>
              </div>

              {/* Action Buttons: Copy Clip & Close X */}
              <div className="flex items-center gap-1.5 sm:gap-2 flex-shrink-0 ml-2">
                <button
                  type="button"
                  onClick={copyFullContent}
                  title="Copy full formula & calculation details to clipboard"
                  className={clsx(
                    'inline-flex items-center gap-1 sm:gap-1.5 px-2 sm:px-2.5 py-1 sm:py-1.5 rounded-lg border text-xs font-mono font-medium transition-all cursor-pointer',
                    copied
                      ? 'border-emerald-500/50 bg-emerald-950/40 text-emerald-300'
                      : 'border-white/[0.08] bg-white/[0.04] text-zinc-300 hover:text-white hover:bg-white/[0.08] hover:border-white/[0.15]'
                  )}
                >
                  {copied ? (
                    <>
                      <Check size={13} className="text-emerald-400 shrink-0" />
                      <span className="text-[10px] sm:text-[11px] text-emerald-300">Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy size={13} className="shrink-0" />
                      <span className="text-[10px] sm:text-[11px] text-zinc-400 hover:text-white">Copy</span>
                    </>
                  )}
                </button>

                <button
                  type="button"
                  onClick={() => setOpen(false)}
                  title="Close modal (Esc)"
                  className="p-1 sm:p-1.5 rounded-lg border border-white/[0.08] bg-white/[0.04] text-zinc-400 hover:text-white hover:bg-white/[0.08] hover:border-white/[0.15] transition-colors cursor-pointer shrink-0"
                >
                  <X size={16} />
                </button>
              </div>
            </div>

            {/* Modal Body */}
            <div className="flex-1 overflow-y-auto p-3.5 sm:p-5 space-y-3 sm:space-y-4">
              {/* Primary Computed Result Card */}
              <div className="rounded-xl border border-indigo-500/20 bg-gradient-to-br from-indigo-950/30 to-purple-950/20 p-3 sm:p-4 flex items-center justify-between">
                <div>
                  <span className="text-[9px] sm:text-[10px] font-mono uppercase tracking-wider text-indigo-300 block">
                    Calculated Result
                  </span>
                  <div className="font-mono text-xl sm:text-2xl font-extrabold text-white tracking-tight mt-0.5">
                    {fullDisplayVal}{' '}
                    <span className="text-xs sm:text-sm font-normal text-indigo-300/80">{metric.unit}</span>
                  </div>
                </div>
                <div className="p-2 sm:p-2.5 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 shrink-0">
                  <Zap size={18} />
                </div>
              </div>

              {/* Formula Expression */}
              <div className="space-y-1.5">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-mono uppercase tracking-wider text-zinc-400 font-semibold">
                    1. Mathematical Formula
                  </span>
                </div>
                <div className="rounded-lg bg-black/60 border border-white/[0.08] p-3 font-mono text-xs text-indigo-300 break-words leading-relaxed selection:bg-indigo-500/30">
                  {metric.formulaText}
                </div>
              </div>

              {/* Step-by-Step Substituted Values */}
              {metric.substitutions && metric.substitutions !== metric.formulaText && (
                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase tracking-wider text-zinc-400 font-semibold">
                    2. Substituted Calculation
                  </span>
                  <div className="rounded-lg bg-black/40 border border-white/[0.06] p-3 font-mono text-xs text-zinc-200 break-words leading-relaxed selection:bg-indigo-500/30">
                    {metric.substitutions}
                  </div>
                </div>
              )}

              {/* Why This Matters / Architecture Context */}
              {metric.humanExplanation && (
                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase tracking-wider text-zinc-400 font-semibold">
                    3. Architectural Context & Sizing Impact
                  </span>
                  <div className="rounded-lg border border-white/[0.06] bg-[#12141f] p-3.5 text-xs text-zinc-300 leading-relaxed">
                    {metric.humanExplanation}
                  </div>
                </div>
              )}

              {/* Dependencies List */}
              {metric.dependsOn.length > 0 && (
                <div className="space-y-1.5 pt-1">
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-mono uppercase tracking-wider text-zinc-400 font-semibold flex items-center gap-1.5">
                      <Layers size={12} className="text-indigo-400" />
                      Upstream Input Dependencies ({metric.dependsOn.length})
                    </span>
                  </div>
                  <div className="flex flex-wrap gap-1.5">
                    {metric.dependsOn.map((dep) => (
                      <span
                        key={dep}
                        title={`Dependency input: ${dep}`}
                        className="inline-flex items-center rounded-md border border-white/[0.08] bg-white/[0.03] px-2 py-1 text-[11px] font-mono text-zinc-300"
                      >
                        {dep}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Modal Footer */}
            <div className="px-5 py-2.5 border-t border-white/[0.08] bg-[#10121b] flex items-center justify-between flex-shrink-0">
              <button
                type="button"
                onClick={() => {
                  if (highlightedDependencies.length > 0) {
                    setHighlightedDependencies([]);
                  } else {
                    setHighlightedDependencies(metric.dependsOn);
                  }
                }}
                className="text-xs font-medium text-indigo-400 hover:text-indigo-300 flex items-center gap-1.5 transition-colors cursor-pointer"
              >
                {highlightedDependencies.length > 0 ? 'Clear Highlight' : 'Trace Dependencies'}
                <ArrowUpRight size={13} />
              </button>

              <button
                type="button"
                onClick={() => setOpen(false)}
                className="px-3 py-1 rounded-md border border-white/[0.08] bg-white/[0.04] text-xs font-medium text-zinc-300 hover:text-white hover:bg-white/[0.08] transition-colors cursor-pointer"
              >
                Close
              </button>
            </div>
          </div>
        </div>,
        document.body
      )}
    </div>
  );
}
